FROM ashael/openmpi
MAINTAINER Eduardo Arango <carlos.arango.gutierrez@correounivalle.edu.co>

RUN apt-get update
RUN apt-get install -y bash wget build-essential gcc time libc6-dev libgcc-5-dev
RUN apt-get install -y libopenmpi-dev openmpi-common openmpi-bin openmpi-doc libatlas3-base libatlas-base-dev libatlas-dev libatlas-doc
RUN wget http://www.netlib.org/benchmark/hpl/hpl-2.2.tar.gz
RUN tar -xvf hpl-2.2.tar.gz -C /usr/local/
RUN mkdir -p /home/benchmark

##Install OpenMPI
RUN mkdir -p $HOME
WORKDIR $HOME
RUN wget --no-check-certificate https://www.open-mpi.org/software/ompi/v2.0/downloads/openmpi-2.0.2.tar.gz
RUN tar -xf openmpi-2.0.2.tar.gz
WORKDIR $HOME/openmpi-2.0.2/build
RUN ../configure --prefix=/usr/local
RUN make clean
RUN make all install


WORKDIR /usr/local/hpl-2.2/
RUN wget --no-check-certificate https://raw.githubusercontent.com/remyd1/containers-benchs/master/linpack/HPL/defs_dockerfiles/dockerfile/HPLtemplate.dat
#ADD HPLtemplate.dat /usr/local/hpl-2.2

RUN sed -i 's|$(LN_S) $(TOPdir)/Make.$(arch) Make.inc|$(LN_S) /usr/local/hpl-2.2/Make.$(arch) Make.inc|' Make.top
RUN mv HPLtemplate.dat Make.Linux

RUN make arch=Linux clean_arch_all
RUN make arch=Linux

WORKDIR /usr/local/hpl-2.2/bin/Linux

CMD bash
