FROM ubuntu:16.04
RUN apt-get update
RUN apt-get install -y bash wget build-essential gcc time libc6-dev libgcc-5-dev
RUN apt-get install -y libopenmpi-dev openmpi-common openmpi-bin openmpi-doc libatlas3-base libatlas-base-dev libatlas-dev libatlas-doc
RUN wget http://www.netlib.org/benchmark/hpl/hpl-2.2.tar.gz
RUN tar -xvf hpl-2.2.tar.gz -C /usr/local/
RUN mkdir -p /home/benchmark

WORKDIR /usr/local/hpl-2.2/
RUN wget --no-check-certificate https://raw.githubusercontent.com/remyd1/containers-benchs/master/linpack/HPL/defs_dockerfiles/dockerfile/HPLtemplate.dat
#ADD HPLtemplate.dat /usr/local/hpl-2.2

RUN sed -i 's|$(LN_S) $(TOPdir)/Make.$(arch) Make.inc|$(LN_S) /usr/local/hpl-2.2/Make.$(arch) Make.inc|' Make.top
RUN mv HPLtemplate.dat Make.Linux

RUN make arch=Linux clean_arch_all
RUN make arch=Linux

WORKDIR /usr/local/hpl-2.2/bin/Linux

CMD bash
